before_script:
    - which angr-test && angr-test sync hard

colorguard:
    script: "angr-test colorguard"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

update_vm_image:
    only: ["master"]
    script:
    - update-vm-image
    tags: ["docker-builder"]
